# Generated by Django 4.2.29 on 2026-04-05 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('transactions', '0002_alter_producttransaction_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colors.color'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
